libs =
#import libs += libhello%lib{hello}

exe{endian}: {hxx ixx txx cxx}{**} $libs testscript

cxx.poptions =+ "-I$out_root" "-I$src_root"

# No macros: Linux:   BYTE_ORDER __BYTE_ORDER
#            FreeBSD: BYTE_ORDER _BYTE_ORDER
#            Macos:   BYTE_ORDER __DARWIN_BYTE_ORDER


cxx.coptions =+ -D_ANSI_SOURCE

# _POSIX_C_SOURCE
# _XOPEN_SOURCE
# _NETBSD_SOURCE
