libs =
#import libs += libhello%lib{hello}

exe{endian}: {hxx ixx txx cxx}{**} $libs testscript

cxx.poptions =+ "-I$out_root" "-I$src_root"

# No headers:      Linux:   __BYTE_ORDER__
#                  FreeBSD: __BYTE_ORDER__
#                  Macos:   __BYTE_ORDER__
#
# No macros:       Linux:   BYTE_ORDER  __BYTE_ORDER         __BYTE_ORDER__
#                  FreeBSD: BYTE_ORDER  _BYTE_ORDER          __BYTE_ORDER__
#                  Macos:   BYTE_ORDER  __DARWIN_BYTE_ORDER  __BYTE_ORDER__
#
# _ANSI_SOURCE:    Linux:   BYTE_ORDER  __BYTE_ORDER         __BYTE_ORDER__
#                  FreeBSD:             _BYTE_ORDER          __BYTE_ORDER__
#                  Macos:   BYTE_ORDER  __DARWIN_BYTE_ORDER  __BYTE_ORDER__
#
# _POSIX_C_SOURCE: Linux:   BYTE_ORDER  __BYTE_ORDER
#                  FreeBSD:             _BYTE_ORDER
#                  Macos:               __DARWIN_BYTE_ORDER
#
# _XOPEN_SOURCE:   Linux:   BYTE_ORDER  __BYTE_ORDER
#                  FreeBSD: BYTE_ORDER  _BYTE_ORDER
#                  Macos:   BYTE_ORDER  __DARWIN_BYTE_ORDER
#
# _NETBSD_SOURCE:  Linux:   BYTE_ORDER  __BYTE_ORDER
#                  FreeBSD: BYTE_ORDER  _BYTE_ORDER
#                  Macos:   BYTE_ORDER  __DARWIN_BYTE_ORDER
#
cxx.coptions =+ -D_POSIX_C_SOURCE
